---
asn: "65103"
evpn_endpoint: 10.0.0.3/32
management: 10.19.30.224/24

vlans:
  - vid: "10"
    vni: "10010"
    name: V0010_CUSTOMER

bgp_peer:
  - neighbor: "10.0.0.0"
    remote_as: "65000"
    group: EVPN
  - neighbor: "10.2.0.4"
    remote_as: "65000"
    group: UNDER

interfaces:
  - name: ge-0/0/0
    template: to_spine.j2
    address: 10.2.0.5/31
  - name: ge-0/0/9
    template: to_customer.j2
    aggrigate: "7"
  - name: ae7
    template: to_customer.j2
    esi: 0022:2222:2222:2200:0000
    allowed_vlan: ["10"]
