---
asn: 65002
evpn_endpoint: 10.0.0.2/32
vxlan_endpoint: 10.1.0.2/32
management: 10.19.30.223/24
uplink_if:
  description: TO:spine-01 Et7
  address: 10.2.0.3/31
vlans:
  - vid: 100
    vni: 10100
    name: CLIENT-NETWORK
bgp_peer:
  - neighbor: 10.0.0.0
    remote_as: 65000
    group: EVPN
  - neighbor: 10.2.0.2
    remote_as: 65000
    group: UNDER
