---
spine:
  hosts:
    spine-01:
      ansible_host: 10.19.30.221
leaf:
  hosts:
    leaf-01:
      ansible_host: 10.19.30.222
    leaf-02:
      ansible_host: 10.19.30.223
    leaf-03:
      ansible_host: 10.19.30.224
arista:
  hosts:
    spine-01:
    leaf-01:
    leaf-02:
juniper:
  hosts:
    leaf-03:
