---
- name: Routing to SONiC
  ansible.builtin.include_tasks: sonic.yml
  when: vender == "sonic"

- name: Routing to arista
  ansible.builtin.include_tasks: arista.yml
  when: ansible_network_os | default(omit)  == "arista.eos.eos"

- name: Routing to juniper
  ansible.builtin.include_tasks: juniper.yml
  when: ansible_network_os | default(omit) == "junipernetworks.junos.junos"
